name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:20240918
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4     
      - name: Setup environment
        run: git config --global safe.directory '*'
      - name: Build
        run: |
          python3 generate_patch.py ${{ github.ref_name }}
          cd action_replay_codes
          zip codes.zip *.txt
          rm *.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cheatcodes
          path: action_replay_codes/

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: cheatcodes
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "RtcPwalker ${{ github.ref_name }}"
          files: artifacts/*
